### ISSUE TITLE
ERROR WHILE RUNNING ON GPU

### ISSUE THREAD

**Issue by anuragdeshmukh** [yuta-hi/pytorch_similarity#1]
Hi, I;m getting this error while running the loss on gpu
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

**Comment by yuta-hi** [comment]
You can copy the module's parameters to device memory as below:
```
device=0 
loss = GradientCorrelationLoss2d().to(device)
```
or
```
loss = GradientCorrelationLoss2d().cuda()
```
